## The Data Science Cluster

Data Science is a new cluster within the Research Services. It includes the following three departments and center:

1. Applications Development & e-Health (ADH)
2. Data Management & Architecture (DMA)
3. Statistics & Computational Bioinformatics (SCB)
3. High Performance Computing (HPC) center

With the increased complexity of data sources, bioinformatics research and the emergence of e-health and artificial intelligence, the present strategic
plan of MRCG (henceforth referred to as the Unit) re-organized the established departments as the key components of a Data Science centre of excellence. This will help to diversify the traditional quantitative role that these departments have had in the past as research support for publication.

In addition to the current research support, the new Data Science Cluster will undertake research using cutting-edge methods, including the application of machine learning with a focus on health and bio-medical problems and translate the academic work of the Unit into tangible e-health and AI public health solutions.

Also, research on climate change and its impact on health will increasingly
depend on a highly complex computational data analysis infrastructure. The Unit plans to leverage the use of AI algorithms in the large amount of health data it has obtained over the decades to provide more accurate diagnosis and treatment of diseases such as TB, pneumonia, and rheumatic heart disease. A key goal of the Data Science cluster is to establish the Unit as a regional and global centre of excellence in health data science and to help expand the funding streams of the current departments.